In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [25]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [12]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'], test_size=0.2, random_state=42);
x_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

## Aam Jindgi

In [ ]:
# treating missing values
from sklearn.impute import SimpleImputer
si = SimpleImputer()

x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [ ]:
# OrdinalEncoding
from sklearn.preprocessing import OrdinalEncoder
oe  = OrdinalEncoder(categories=[['Mild','Strong']])

x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [ ]:
#OneHotEncoding
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False) # Multicolleniarity

x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])
x_test_gender_city = ohe.fit_transform(x_test[['gender', 'city']])

x_train_gender_city.shape

(80, 4)

In [31]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender', 'fever','cough', 'city']).values
x_test_age = x_test.drop(columns=['gender', 'fever','cough', 'city']).values
x_train_age.shape

(80, 1)

In [39]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed

array([[ 81., 101.,   0.,   0.,   0.,   1.,   0.],
       [  5., 100.,   0.,   0.,   1.,   0.,   0.],
       [ 19., 100.,   0.,   0.,   1.,   0.,   0.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 73., 103.,   0.,   1.,   0.,   0.,   0.],
       [ 70., 103.,   1.,   0.,   1.,   0.,   1.],
       [ 49., 102.,   0.,   1.,   0.,   0.,   0.],
       [ 51., 101.,   0.,   0.,   1.,   0.,   1.],
       [ 64., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 83., 101.,   0.,   0.,   1.,   0.,   0.],
       [ 65.,  98.,   0.,   0.,   0.,   1.,   0.],
       [ 18., 104.,   0.,   0.,   0.,   0.,   0.],
       [ 16., 103.,   0.,   0.,   0.,   0.,   0.],
       [ 16., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 27., 100.,   1.,   0.,   1.,   0.,   0.],
       [ 84., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 51., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 69., 102.,   0.,   0.,   0.,   0.,   0.],
       [ 82., 102.,   0.,   0.,   0.,   0.,   1.],
       [ 69., 103.,   0.,   0.,   1.,   0.,   0.],
       [ 44., 104.,   1.,   0.,   0.,   1.,   0.],
       [ 74., 102.,   1.,   0.,   0.,   1.,   0.],
       [ 20., 101.,   0.,   0.,   0.,   1.,   1.],
       [ 12., 104.,   0.,   0.,   0.,   0.,   0.],
       [ 33., 102.,   0.,   1.,   0.,   0.,   1.],
       [ 42., 101.,   0.,   0.,   0.,   0.,   1.],
       [ 65.,  99.,   1.,   1.,   0.,   0.,   0.],
       [ 23., 101.,   1.,   0.,   0.,   1.,   0.],
       [ 56., 104.,   0.,   0.,   0.,   0.,   1.],
       [ 64., 102.,   1.,   0.,   0.,   0.,   0.],
       [ 13., 100.,   0.,   0.,   1.,   0.,   1.],
       [ 31.,  98.,   0.,   0.,   1.,   0.,   0.],
       [ 40.,  98.,   0.,   1.,   0.,   0.,   1.],
       [ 49., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 19., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 11., 100.,   1.,   0.,   0.,   0.,   0.],
       [ 14., 101.,   1.,   0.,   0.,   0.,   1.],
       [ 42., 104.,   1.,   0.,   0.,   1.,   0.],
       [ 38., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 46., 103.,   1.,   0.,   0.,   0.,   1.],
       [ 71., 101.,   1.,   0.,   1.,   0.,   1.],
       [ 10.,  98.,   0.,   0.,   1.,   0.,   1.],
       [ 60.,  99.,   0.,   0.,   0.,   1.,   0.],
       [ 22.,  99.,   0.,   0.,   0.,   0.,   0.],
       [ 19., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 65.,  99.,   1.,   0.,   0.,   0.,   0.],
       [ 19., 101.,   0.,   0.,   0.,   1.,   0.],
       [ 54., 104.,   0.,   0.,   1.,   0.,   1.],
       [ 81.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 20., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 48., 103.,   0.,   0.,   1.,   0.,   0.],
       [ 82., 101.,   1.,   0.,   1.,   0.,   0.],
       [ 23.,  98.,   1.,   0.,   0.,   1.,   1.],
       [ 66.,  99.,   1.,   0.,   0.,   0.,   1.],
       [  5.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 49.,  99.,   0.,   0.,   0.,   0.,   1.],
       [  5., 102.,   1.,   0.,   1.,   0.,   0.],
       [ 34., 101.,   0.,   1.,   0.,   0.,   1.],
       [ 79., 101.,   1.,   0.,   1.,   0.,   1.],
       [  6., 104.,   0.,   0.,   1.,   0.,   0.],
       [ 10., 100.,   1.,   0.,   0.,   0.,   0.],
       [ 69.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 55., 100.,   1.,   0.,   1.,   0.,   0.],
       [ 34., 101.,   0.,   0.,   0.,   1.,   1.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 47., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 73.,  98.,   1.,   0.,   0.,   0.,   0.],
       [ 42., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 80.,  98.,   0.,   1.,   0.,   0.,   0.],
       [ 47., 101.,   1.,   0.,   0.,   0.,   1.],
       [ 38., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 34., 104.,   0.,   1.,   0.,   0.,   1.],
       [ 25., 104.,   1.,   0.,   0.,   0.,   0.],
       [ 24.,  98.,   1.,   0.,   1.,   0.,   0.],
       [ 12.,  98.,   1.,   0.,   0.,   0.,   1.],
       [ 24., 102.,   0.,   0.,   0.,   0.,   1.],
       [ 75., 104.,   0.,   1.,   0.,   0.,   1.],
       [ 51., 104.,   1.,   0.,   0.,   0.,   0.],
       [ 82., 102.,   0.,   0.,   1.,   0.,   1.],
       [ 11., 100.,   0.,   0.,   1.,   0.,   1.]])

## Mentos Jindgi

In [35]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False),['gender','city'])
], remainder='passthrough')

In [40]:
transformer.fit_transform(x_train)

array([[101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [101.,   1.,   0.,   0.,   0.,   1.,  20.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [102.,   0.,   1.,   0.,   0.,   0.,  64.],
       [100.,   1.,   0.,   0.,   1.,   0.,  13.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  31.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [100.,   0.,   1.,   0.,   0.,   0.,  11.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [104.,   0.,   1.,   0.,   0.,   1.,  42.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [101.,   1.,   1.,   0.,   1.,   0.,  71.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [101.,   0.,   1.,   1.,   0.,   0.,  19.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [104.,   1.,   0.,   0.,   1.,   0.,  54.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [101.,   0.,   1.,   0.,   1.,   0.,  82.],
       [ 98.,   1.,   1.,   0.,   0.,   1.,  23.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [101.,   1.,   0.,   1.,   0.,   0.,  34.],
       [101.,   1.,   1.,   0.,   1.,   0.,  79.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  69.],
       [100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [101.,   1.,   0.,   0.,   0.,   1.,  34.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [100.,   1.,   0.,   0.,   0.,   0.,  47.],
       [ 98.,   0.,   1.,   0.,   0.,   0.,  73.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [101.,   0.,   1.,   1.,   0.,   0.,  38.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [104.,   0.,   1.,   0.,   0.,   0.,  25.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [104.,   0.,   1.,   0.,   0.,   0.,  51.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.]])

In [42]:
transformer.transform(x_test).shape

(20, 7)